### Partie 1 : SERIES

In [101]:
import pandas as pd
import numpy as np

##### 1) Créer une Series contenant 4 températures

In [102]:
temperature = pd.Series([20, 25, 32, 36],
index=["1", "2", "3", "4"])
print(temperature)

1    20
2    25
3    32
4    36
dtype: int64

##### 3) Afficher la 1ère valeur

In [103]:
print(temperature["1"])

20

##### 4) Afficher la dernière valeur

In [104]:
print(temperature["4"])

36

##### 5) Créer, de deux façon différentes, une Series de 4 températures avec comme index les heures de mesure 12h, 13h, 14h et 15h

##### premiere facon

In [105]:
temp_1 = pd.Series([15, 20, 35, 40],
index= ["12h", "13h", "14h", "15h"])
print(temp_1)

12h    15
13h    20
14h    35
15h    40
dtype: int64

##### Deuxieme facon

In [106]:
temp_2 = {
    "12h":15,
    "13h":20,
    "14h":35,
    "15h":40
}
temp_2= pd.Series(temp_2)
print(temp_2)

12h    15
13h    20
14h    35
15h    40
dtype: int64

##### 6) Afficher la 1ère et la dernière valeur

In [107]:
print(temp_2["12h"])
print(temp_2["15h"])

15
40

##### Partie 2 – DataFrame

##### 1) Créer et afficher le dataframe df_test à partir du dictionnaire suivant

In [108]:
data = {
    "capteur":["c001", "c002", "c003"],
    "temperature":[24.5, 25.1, 26.3],
    "humidite":[65, 67, 70]
}
df_test = pd.DataFrame(data)
print(df_test)

  capteur  temperature  humidite
0    c001         24.5        65
1    c002         25.1        67
2    c003         26.3        70

##### 2) Importer le dataset mesures_capteurs.csv dans le dataframe df

In [109]:
df = pd.read_csv('../data/mesures_capteurs.csv')
print(df)

    id_mesure           date_heure id_capteur batiment  temperature  humidite  \
0       M0413  2026-01-22 04:00:00       C005     B002        25.46     58.06
1       M0290  2026-01-17 01:00:00       C002     B001        24.00     79.73
2       M0077  2026-01-08 04:00:00       C005     B002        25.82     54.47
3       M0079  2026-01-08 06:00:00       C007     B003        28.23     69.39
4       M0183  2026-01-12 14:00:00       C003     B001        20.58     53.80
..        ...                  ...        ...      ...          ...       ...
600     M0072  2026-01-07 23:00:00       C012     B004        23.67     60.28
601     M0107  2026-01-09 10:00:00       C011     B004        24.34     61.42
602     M0271  2026-01-16 06:00:00       C007     B003        23.73     63.49
603     M0436  2026-01-23 03:00:00       C004     B002        24.83     79.77
604     M0103  2026-01-09 06:00:00       C007     B003        17.02     52.04

     pression  consommation etat
0     1008.95        287.28   OK
1      993.39        116.20   OK
2     1010.32        288.50   OK
3     1019.62        136.65   OK
4     1016.58        182.62   OK
..        ...           ...  ...
600   1015.11        282.36   OK
601   1019.43        357.43   OK
602   1016.46        152.79   OK
603   1017.05        170.97   OK
604   1001.14         44.99   OK

[605 rows x 9 columns]

##### 3) Afficher les dimensions de df

In [110]:
print(df.shape)

(605, 9)

***explication***: ce resultat represente le nombre de ligne et de colonnes que la dataframe df a.

##### Partie 3 – Exploration

##### 1) Afficher les premières lignes

In [111]:
print(df.head())

  id_mesure           date_heure id_capteur batiment  temperature  humidite  \
0     M0413  2026-01-22 04:00:00       C005     B002        25.46     58.06
1     M0290  2026-01-17 01:00:00       C002     B001        24.00     79.73
2     M0077  2026-01-08 04:00:00       C005     B002        25.82     54.47
3     M0079  2026-01-08 06:00:00       C007     B003        28.23     69.39
4     M0183  2026-01-12 14:00:00       C003     B001        20.58     53.80

   pression  consommation etat
0   1008.95        287.28   OK
1    993.39        116.20   OK
2   1010.32        288.50   OK
3   1019.62        136.65   OK
4   1016.58        182.62   OK

##### 2) Afficher les 10 premières lignes

In [112]:
print(df.head(10))

  id_mesure           date_heure id_capteur batiment  temperature  humidite  \
0     M0413  2026-01-22 04:00:00       C005     B002        25.46     58.06
1     M0290  2026-01-17 01:00:00       C002     B001        24.00     79.73
2     M0077  2026-01-08 04:00:00       C005     B002        25.82     54.47
3     M0079  2026-01-08 06:00:00       C007     B003        28.23     69.39
4     M0183  2026-01-12 14:00:00       C003     B001        20.58     53.80
5     M0595  2026-01-29 18:00:00       C007     B003        24.51     58.01
6     M0011  2026-01-05 10:00:00       C011     B004        29.23     70.43
7     M0132  2026-01-10 11:00:00       C012     B004        31.21     60.57
8     M0444  2026-01-23 11:00:00       C012     B004        23.11     82.06
9     M0087  2026-01-08 14:00:00       C003     B001        28.85     44.37

   pression  consommation etat
0   1008.95        287.28   OK
1    993.39        116.20   OK
2   1010.32        288.50   OK
3   1019.62        136.65   OK
4   1016.58        182.62   OK
5   1013.34        146.10   OK
6   1007.68        290.45   OK
7   1024.64        285.92   OK
8   1021.96        293.36   OK
9   1008.27        206.59   OK

##### 3) Afficher les dernières lignes

In [113]:
print(df.tail())

    id_mesure           date_heure id_capteur batiment  temperature  humidite  \
600     M0072  2026-01-07 23:00:00       C012     B004        23.67     60.28
601     M0107  2026-01-09 10:00:00       C011     B004        24.34     61.42
602     M0271  2026-01-16 06:00:00       C007     B003        23.73     63.49
603     M0436  2026-01-23 03:00:00       C004     B002        24.83     79.77
604     M0103  2026-01-09 06:00:00       C007     B003        17.02     52.04

     pression  consommation etat
600   1015.11        282.36   OK
601   1019.43        357.43   OK
602   1016.46        152.79   OK
603   1017.05        170.97   OK
604   1001.14         44.99   OK

##### 4) Afficher le nombre de lignes

In [114]:
print(len(df))

605

##### 5) Afficher le nombre de colonnes

In [115]:
print(len(df.columns))

9

##### 6) Afficher les noms des colonnes

In [116]:
print(df.columns.tolist())

['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature', 'humidite', 'pression', 'consommation', 'etat']

##### 7) Afficher les informations générales

In [117]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB
None

##### 8) Afficher les statistiques descriptives

In [118]:
print(df.describe())

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

***explication***: la fonction describe() permet d'afficher les statistiques descriptives de la dataframe df. le calcul est fait en arriere plan et affiche la moyenne , l'ecart-type , le minimum , le maximum, le Q1 ,Q2 et Q3...

### Partie 4 – Sélection

##### 1) Sélectionner la colonne "temperature"

In [119]:
df[['temperature']]

     temperature
0          25.46
1          24.00
2          25.82
3          28.23
4          20.58
..           ...
600        23.67
601        24.34
602        23.73
603        24.83
604        17.02

[605 rows x 1 columns]

##### 2) Sélectionner les colonnes "temperature", "humidite", "pression" et "consommation"

In [120]:
# Sélectionner plusieurs colonnes spécifiques
df[['temperature', 'humidite', 'pression', 'consommation']]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

##### 3) Sélectionner les 5 premières lignes avec loc

In [121]:
print(df.loc[0:4])

  id_mesure           date_heure id_capteur batiment  temperature  humidite  \
0     M0413  2026-01-22 04:00:00       C005     B002        25.46     58.06
1     M0290  2026-01-17 01:00:00       C002     B001        24.00     79.73
2     M0077  2026-01-08 04:00:00       C005     B002        25.82     54.47
3     M0079  2026-01-08 06:00:00       C007     B003        28.23     69.39
4     M0183  2026-01-12 14:00:00       C003     B001        20.58     53.80

   pression  consommation etat
0   1008.95        287.28   OK
1    993.39        116.20   OK
2   1010.32        288.50   OK
3   1019.62        136.65   OK
4   1016.58        182.62   OK

##### 4) Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc

In [122]:
print(df.iloc[0:5, 0:4])

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

##### Partie 5 – Manipulation des colonnes

##### 1) Ajouter la colonne "temperature_fahrenheit"

In [123]:
df['temperature_fahrenheit']= 0
print(df)

    id_mesure           date_heure id_capteur batiment  temperature  humidite  \
0       M0413  2026-01-22 04:00:00       C005     B002        25.46     58.06
1       M0290  2026-01-17 01:00:00       C002     B001        24.00     79.73
2       M0077  2026-01-08 04:00:00       C005     B002        25.82     54.47
3       M0079  2026-01-08 06:00:00       C007     B003        28.23     69.39
4       M0183  2026-01-12 14:00:00       C003     B001        20.58     53.80
..        ...                  ...        ...      ...          ...       ...
600     M0072  2026-01-07 23:00:00       C012     B004        23.67     60.28
601     M0107  2026-01-09 10:00:00       C011     B004        24.34     61.42
602     M0271  2026-01-16 06:00:00       C007     B003        23.73     63.49
603     M0436  2026-01-23 03:00:00       C004     B002        24.83     79.77
604     M0103  2026-01-09 06:00:00       C007     B003        17.02     52.04

     pression  consommation etat  temperature_fahrenheit
0     1008.95        287.28   OK                       0
1      993.39        116.20   OK                       0
2     1010.32        288.50   OK                       0
3     1019.62        136.65   OK                       0
4     1016.58        182.62   OK                       0
..        ...           ...  ...                     ...
600   1015.11        282.36   OK                       0
601   1019.43        357.43   OK                       0
602   1016.46        152.79   OK                       0
603   1017.05        170.97   OK                       0
604   1001.14         44.99   OK                       0

[605 rows x 10 columns]

##### 2) Ajouter la colonne "niveau_temperature" pour catégoriser la température en Élevée (température > 30) ou Normale".

In [129]:
df['niveau_temperature']= np.where(df['temperature'] > 30, 'Elevee', 'Normale')
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat,temperature_fahrenheit,niveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,0,Normale
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,0,Normale
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,0,Normale
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,0,Normale
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,0,Normale